$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command

# The script to run
code: ../src
command: >
  python train.py 
  --train_data ${{inputs.train_data}} 
  --val_data ${{inputs.val_data}} 
  --test_data ${{inputs.test_data}} 
  --output ${{outputs.model_output}}

# Inputs (using your registered Data Assets)
inputs:
  train_data:
    type: uri_folder
    path: azureml:amazon_review_merged_features_train@latest
  val_data:
    type: uri_folder
    path: azureml:amazon_review_merged_features_val@latest
  test_data:
    type: uri_folder
    path: azureml:amazon_review_merged_features_test@latest

# Output for the model artifact
outputs:
  model_output:
    type: uri_folder

# Environment & Compute
environment:
  build:
    local_path: ../env
compute: azureml:lab4-cluster
display_name: amazon_review_model_training
experiment_name: amazon_review_sentiment_analysis