name: model_training_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - pip
  - pyarrow # Needed to read Parquet files
  - pip:
    - mlflow
    - azureml-mlflow